version: "3.7"

services:
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: dev

volumes:
  mongodb:
